### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvr-polyfill-dpdb#15]

**Comment by cvan** [comment]
added to npm: https://www.npmjs.com/package/webvr-polyfill-dpdb

(using the same version of `webvr-polyfill`, to keep things simple.)

@thoragio and @jsantell: added y'all.

anyone else need access? just let me know your npm username.

**Comment by jsantell** [comment]
:+1: Now we can just pull this in in webvr-polyfill, awesome

**Comment by thoragio** [comment]
@cvan I tried publishing v1.0.0 to npm but I got a permission error:

`npm ERR! you do not have permission to publish "webvr-polyfill-dpdb". Are you logged in as the correct user? : webvr-polyfill-dpdb`

I am logged into npm correctly:

```
$ npm whoami
thoragio
```

Can you check the permissions, or just push v1 to the registry directly? Thanks.

**Comment by jsantell** [comment]
@thoragio published 1.0.0, and added you as owner as well!

**Comment by thoragio** [comment]
@jsantell Awesome. Thanks a lot!
