### ISSUE TITLE
Change versioning scheme

### ISSUE THREAD

**Issue by jsantell** [WebVRRocks/webvr-polyfill-dpdb#18]
Right now this version is tracking the [webvr-polyfill](https://github.com/googlevr/webvr-polyfill) version 0.9.27, but this seems unsustainable, as the polyfill is now 0.9.28, and in the case where the polyfill is using the dpdb as a dependency, like it could get confusing.

I propose for simplicity, just publishing 1.0.0, and incrementing patch versions with new devices from there, and the polyfill can bump dependencies when needed.

@cvan thoughts?

**Comment by cvan** [comment]
yeah, that seems fine
