### ISSUE TITLE
Please add an entry for the Samsung S8+

### ISSUE THREAD

**Issue by aaronanderson** [WebVRRocks/webvr-polyfill-dpdb#23]
{"type":"android","rules":[{"mdmh":"samsung/*/SM-G955U/*"},{"ua":"SM-G955U"}],"dpi":[522.514,525.762],"bw":3,"ac":500},

**Comment by thoragio** [comment]
@aaronanderson I've added the device with the settings you submitted above. Can you please try the updated dpdb file and confirm if it works correctly? Thanks.

**Comment by thoragio** [comment]
Added in version 1.0.2
