### ISSUE TITLE
Please add entry for Samsung Galaxy S8

### ISSUE THREAD

**Issue by markqvist** [WebVRRocks/webvr-polyfill-dpdb#25]
Here's an entry for the Galaxy S8. Could you please add it to the dpdb?

{"type":"android","rules":[{"mdmh":"samsung//SM-G950F/"},{"ua":"SM-G950F"}],"dpi":[562.707,565.293],"bw":3,"ac":500},

**Comment by thoragio** [comment]
Added in version 1.0.2
