### ISSUE TITLE
Please add SM-N920P

### ISSUE THREAD

**Issue by patrouss** [WebVRRocks/webvr-polyfill-dpdb#26]
Please add Note5 SM-N920P :
 {
       "type": "android",
       "rules": [
         {
           "mdmh": "samsung/*/SM-N920P/*"
         },
         {
           "ua": "SM-N920P"
         }
       ],
       "dpi": [
         386.3655,
         390.144
       ],
       "bw": 3,
       "ac": 1000
     },

**Comment by jsantell** [comment]
Thanks for reporting!
