### ISSUE TITLE
Please add Motorola G5 Plus

### ISSUE THREAD

**Issue by tomkuipers** [WebVRRocks/webvr-polyfill-dpdb#27]
{ 
      "type": "android",
      "rules": [
        {
          "mdmh": "motorola/*/G5/*"
        },
        {
          "ua": "Moto G (5) Plus"
        }
      ],
      "dpi": [
        403.4,
        403
      ],
      "bw": 3,
      "ac": 1000
    }

**Comment by jsantell** [comment]
Thanks for reporting! Fixed via 3dcd8b7638818f77f0a92bbdbb537d3288a252f5
