### ISSUE TITLE
Issue with Galaxy S7

### ISSUE THREAD

**Issue by AdrienPoupa** [WebVRRocks/webvr-polyfill-dpdb#3]
Hello,

First of all, thanks for creating this repo!

However, when I try to use your compiled version of Aframe (https://rawgit.com/thoragio/vr-aframe-dist/master/040/aframe-v0.4.0.min.js) with a Samsung Galaxy S7 the image is still distorded/duplicated in a cardboard, despite your additions.

http://btco-code.appspot.com/debug/screen_test.html returns

UA: Mozilla/5.0 (Linux; Android 6.0.1; SM-G935F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36
computed resolution: 2560 x 1440
screen.width: 640
screen.height: 360
screen.availWidth: 640
screen.availHeight: 360
window.devicePixelRatio: 4

Is there anything that can be fixed?

Thank you!

**Comment by thoragio** [comment]
Hi, you have the exact same phone as me! Did you clear the cache when you updated your app to use my compiled version of A-Frame? I've had to go into `Settings > Privacy > Clear browsing data` and then `clear cached images and files` or my app would still use the previous version of A-Frame.

**Comment by AdrienPoupa** [comment]
Thanks for the reply. Unfortunately it didn't help. I'm using it to display the default a-sky.

**Comment by thoragio** [comment]
Can you show me your code so I can try to replicate the problem?

**Comment by AdrienPoupa** [comment]
It is located here: http://loc.diagamter.com/testcardboard.html

On my OnePlus One, everything works just fine, but the view with the S7 is distorted.

**Comment by thoragio** [comment]
I tested the page and was getting an error in the DPDB loader. I made a slight modification to the DPDB online cache file. I've tested it and it seems to be working fine now. Please try on your side and let me know.

Also, follow the steps above to clear your cache so that you get the latest DPDB cache file that I have updated.

**Comment by AdrienPoupa** [comment]
Awesome, it works! Many thanks.

I've also tried with an iPhone 6S and the image looks fine until I enter VR mode. Then, the image looks blurry, I assume this is related to this? https://github.com/aframevr/aframe/issues/2008 In this case, is there anything that I can do to help?

Otherwise, can I simply use the 0.3.2 version and your DPDB cache?

**Comment by thoragio** [comment]
Great!

Yes, the blur is related to that other issue. If you have some experience dealing with npm packages, check out the end of the discussion thread for that issue thread to see if you have any ideas. I am going to take a look at it when I get a chance.

In the meantime, you can just replace the Google DPDB URL in the 0.3.2 version with the URL to my repo and it will work fine. Or just use the one I've just updated here: https://github.com/thoragio/vr-aframe-dist

The URL you can use is: https://rawgit.com/thoragio/vr-aframe-dist/master/032/aframe-v0.3.2.min.js

Let me know if you have any issues with it when you test it on your iPhone 6S.

**Comment by AdrienPoupa** [comment]
Once again, thank you. I don't own an IPhone personally which makes it hard for me to debug but I'll let you know if I face any issue.

**Comment by thoragio** [comment]
OK. Thanks again for flagging this up.
