### ISSUE TITLE
Add iPhone X (and other recent devices)

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvr-polyfill-dpdb#33]
[This chat message](https://webvr.slack.com/archives/C0EEECMA5/p1518643733000179) was posted in the `#general` channel of the [WebVR Slack](https://webvr.slack.com/):

> jasonmarsh [1 day ago]
> I'm looking to get the webvr-polyfill device params updated to work with the latest phones. Here's what I know because it might help someone, and what I Both my app and the a-frame examples have horrible aspect ratios and eye distance on iPhone X).  I fixed a few Samsung phones (SM-G930V and SM-G950U - my AT&T S8 ) by adding entries into the device params database (dpdb). 
> 
> Looking here: https://dpdb.webvr.rocks/dpdb.json, I can see the following entries for iOS devices, which list the screen resolution in order to figure out which device it is:
This is the entry for iPhone 8: {"type":"ios","rules":[{"res":[1242,2208]}],"dpi":[453.6,458.4],"bw":4,"ac":1000}
The entry for iPhone X, which is missing, should be a res of 1126, 2436, with approx a dpi of 458. (I'm not sure of the source for the more precise dpi value).
> 
> Who maintains the dpdb at webvr.rocks? Can we update it with the iphoneX values, or actually do a survey of current phones and see what is missing?

**Comment by cvan** [comment]
an update:

> jasonmarsh [2:12 PM]
> values as actually reported by iphoneX:
> {"type":"ios","rules":[{"res":[1125,2436]}],"dpi":458,"bw":4,"ac":1000}
> This works MUCH better!

**Comment by azmartone** [comment]
@thoragio. I think https://github.com/immersive-web/webvr-polyfill-dpdb/pull/35 is ready for merge :)

**Comment by cvan** [comment]
merged, thanks for ping!

**Comment by thoragio** [comment]
Thank you @cvan @azmartone 

Somehow I missed this PR. Apologies.
