### ISSUE TITLE
Samsung variants

### ISSUE THREAD

**Issue by marshworks** [WebVRRocks/webvr-polyfill-dpdb#37]
Having purchased dozens of Samsung phones for GearVR customers, I have personally these variants of IDs. Two of the below are S7s and the last is an S8 (AT&T version), so I created these:
  {"type":"android","rules":[{"mdmh":"samsung/*/SM-G930A/*"},{"ua":"SM-G930A"}],"dpi":576.6,"bw":3,"ac":1000}, 
  {"type":"android","rules":[{"mdmh":"samsung/*/SM-G930V/*"},{"ua":"SM-G930V"}],"dpi":576.6,"bw":3,"ac":1000}, 
  {"type":"android","rules":[{"mdmh":"samsung/*/SM-G950U/*"},{"ua":"SM-G950U"}],"dpi":[562.707,565.293],"bw":3,"ac":500},

But, Samsung generates many, many id variants which appear in the userAgent string:
Here's a list I found online:
https://forum.xda-developers.com/galaxy-s8/how-to/index-list-s8-s8-versions-t3586387

Perhaps we should query for the model without the trailing alpha character?
Such as SM-930 instead of SM-930A?

**Comment by jsantell** [comment]
Fixed via immersive-web/cardboard-vr-display#30
