### ISSUE TITLE
Needs LICENSE

### ISSUE THREAD

**Issue by jsantell** [WebVRRocks/webvr-polyfill-dpdb#4]
I'm guessing this should be Apache from [webvr-polyfill](https://github.com/googlevr/webvr-polyfill/blob/master/COPYING), but should be clear about that, and have some patches for this repo but need an explicit license first :)

**Comment by jsantell** [comment]
Ping @cvan @thoragio

**Comment by jsantell** [comment]
Thanks @cvan!

**Comment by cvan** [comment]
np, thanks for filing 😄
