### ISSUE TITLE
Could we add support for iPhone XS Max?

### ISSUE THREAD

**Issue by maggiecopyAWS** [WebVRRocks/webvr-polyfill-dpdb#50]
I need support for iPhone XS Max. Was not able to send pull request because of authentication failure. Could anyone help to add the following? Thanks.

    {
     "type": "ios",
      "rules": [
        {
          "res": [
            1242,
            2688
          ]
        }
      ],
      "dpi": 458,
      "bw": 4,
      "ac": 1000
    },

**Comment by mattrei** [comment]
I have added a PR for this!

**Comment by jsantell** [comment]
Closed via #51
